class Local_Dimension
{
    constructor(inline, crossline, depth, downfactor)
    {
        // make sure the main dimension inputs are valid
        if (inline && inline <= 0) { throw new Error('inline should not be 0'); }
        if (crossline && crossline <= 0) { throw new Error('crossline should not be 0'); }
        if (depth && depth <= 0) { throw new Error('depth should not be 0'); }

        this.inline = inline;
        this.crossline = crossline;
        this.depth = depth;

        this.start = Object.create(null, {
            inline:    { value: +this.inline/2, writable: false, enumerable: false },
            crossline: { value: -this.crossline/2, writable: false, enumerable: false },
            depth:     { value: +this.depth/2, writable: false, enumerable: false },
        });

        this.stop = Object.create(null, {
            inline:    { value: -this.inline/2, writable: false, enumerable: false },
            crossline: { value: +this.crossline/2, writable: false, enumerable: false },
            depth:     { value: -this.depth/2, writable: false, enumerable: false },
        });

        this.downfactor = downfactor;

        this.inline_start = -(inline/downfactor);
        this.inline_stop  =  (inline/downfactor);

        this.crossline_start = -(crossline/downfactor);
        this.crossline_stop  =  (crossline/downfactor);

        this.depth_start = -(depth/downfactor);
        this.depth_stop  =  (depth/downfactor);

    }
}


/** NOTE: This doc were generated by AI-DeepSeek.
* Creates a configuration object for 3D dimension rendering with computed bounds.
* This function validates input dimensions and returns an immutable configuration object
* containing original dimensions and computed start/stop values for 3D rendering.
*
* @typedef {Object} DimensionInputData
* @property {number} [inline=10] - Number of inline units (must be > 0)
* @property {number} [crossline=10] - Number of crossline units (must be > 0)
* @property {number} [depth=10] - Depth units (must be > 0)
* @property {number} [downFactor=5] - Scaling factor for computing bounds
*
* @typedef {Object} DimensionRenderData
* @property {number} inline - Original inline dimension (non-enumerable, read-only)
* @property {number} crossline - Original crossline dimension (non-enumerable, read-only)
* @property {number} depth - Original depth dimension (non-enumerable, read-only)
* @property {number} downFactor - Original downFactor (non-enumerable, read-only)
* @property {number} inline_start - Computed: -(inline/downFactor)
* @property {number} inline_stop - Computed: +(inline/downFactor)
* @property {number} crossline_start - Computed: -(crossline/downFactor)
* @property {number} crossline_stop - Computed: +(crossline/downFactor)
* @property {number} depth_start - Computed: -(depth/downFactor)
* @property {number} depth_stop - Computed: +(depth/downFactor)
*
* @param {DimensionInputData} [data={}] - Input dimension configuration
* @param {number} [data.inline=10] - Inline dimension
* @param {number} [data.crossline=10] - Crossline dimension
* @param {number} [data.depth=10] - Depth dimension
* @param {number} [data.downFactor=5] - Downscaling factor
*
* @returns {DimensionRenderData} Immutable render configuration object
*
* @throws {Error} When any dimension is less than or equal to 0
*
* @example
* const config = createLocalDimensionData({
*   inline: 20,
*   crossline: 30,
*   depth: 40,
*   downFactor: 4
* });
* console.log(config.inline_start); // -5
* console.log(config.inline_stop);  // 5
*/
function createLocalDimensionData( data = {
    inline: 10,
    crossline: 10,
    depth: 10,
    downFactor: 5,
})
{

    // make sure the main dimension inputs are valid
    if (!Number.isFinite(data.inline) || data.inline <= 0) { throw new Error('data.inline should not be 0'); }
    if (!Number.isFinite(data.crossline) || data.crossline <= 0) { throw new Error('data.crossline should not be 0'); }
    if (!Number.isFinite(data.depth) || data.depth <= 0) { throw new Error('data.depth should not be 0'); }
    if (!Number.isFinite(data.downFactor) || data.downFactor <= 0) { throw new Error('data.downFactor should not be 0'); }

    const renderData = Object.create(null, {

        inline:          { value: data.inline, writeable: false, enumerable: false },
        crossline:       { value: data.crossline, writeable: false, enumerable: false },
        depth:           { value: data.depth, writeable: false, enumerable: false },
        downFactor:      { value: data.downFactor, writeable: false, enumerable: false },

        // bounds by downfactor
        inline_start:    { value: -((data.inline/data.downFactor)), writeable: false, enumerable: false },
        inline_stop:     { value: +((data.inline/data.downFactor)), writeable: false, enumerable: false },
        crossline_start: { value: -((data.crossline/data.downFactor)), writeable: false, enumerable: false },
        crossline_stop:  { value: +((data.crossline/data.downFactor)), writeable: false, enumerable: false },
        depth_start:     { value: +((data.depth/data.downFactor)), writeable: false, enumerable: false },
        depth_stop:      { value: -((data.depth/data.downFactor)), writeable: false, enumerable: false },

        // start stop index, does not scaled by the downfactor
        // so we can still use raw index sent from python, the actual
        // array indexing e.g., for 3D array -> array[10, :, :]
        start:           {
            value: Object.create(null, {
                inline:    { value: +data.inline/2, writable: false, enumerable: false },
                crossline: { value: -data.crossline/2, writable: false, enumerable: false },
                depth:     { value: +data.depth/2, writable: false, enumerable: false },
            }),
            writable: false,
            enumrable: false
        },
        stop:           {
            value: Object.create(null, {
                inline:    { value: -data.inline/2, writable: false, enumerable: false },
                crossline: { value: +data.crossline/2, writable: false, enumerable: false },
                depth:     { value: -data.depth/2, writable: false, enumerable: false },
            }),
            writable: false,
            enumrable: false

        },

    });

    return renderData;
}

export { createLocalDimensionData };
